# Generated by Django 4.2.13 on 2026-05-19 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                ("motivo", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("cancelada", "Cancelada"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="ativa",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="rooms.sala",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reservas",
                "ordering": ["-data", "-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criada", "Criada"),
                            ("cancelada", "Cancelada"),
                            ("editada", "Editada"),
                            ("finalizada", "Finalizada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="reservations.reserva",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Históricos de Reserva",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="CancelamentoReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField()),
                ("data_cancelamento", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelamentos_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancelamento",
                        to="reservations.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cancelamentos de Reservas",
            },
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["sala", "data", "hora_inicio"],
                name="reservation_sala_id_fbc7a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["professor", "data"], name="reservation_profess_45a912_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["data", "status"], name="reservation_data_c9dd40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historicoreserva",
            index=models.Index(
                fields=["reserva", "data_hora"], name="reservation_reserva_d76f48_idx"
            ),
        ),
    ]
