# Generated by Django 4.2.13 on 2026-06-02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cancelamentoreserva",
            old_name="titulo",
            new_name="motivo",
        ),
    ]
