# Generated by Django 4.2.13 on 2026-06-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_cancelamentoreserva_titulo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cancelamentoreserva",
            name="titulo",
        ),
    ]
