# Generated by Django 4.2.13 on 2026-06-02 14:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_remove_cancelamentoreserva_titulo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cancelamentoreserva",
            old_name="motivo",
            new_name="titulo",
        ),
    ]
