# Generated by Django 4.2.13 on 2026-06-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_rename_cancelamentoreserva_motivo_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancelamentoreserva",
            name="titulo",
            field=models.CharField(max_length=255),
        ),
    ]
