# Generated by Django 4.2.13 on 2026-05-19 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Recursos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("predio", models.CharField(max_length=100)),
                ("andar", models.IntegerField()),
                ("capacidade", models.PositiveIntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("ativa", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "recursos",
                    models.ManyToManyField(
                        blank=True, related_name="salas", to="rooms.recurso"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Salas",
                "ordering": ["predio", "andar", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                ("motivo", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("cancelada", "Cancelada"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="ativa",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="rooms.sala",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reservas",
                "ordering": ["-data", "-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criada", "Criada"),
                            ("cancelada", "Cancelada"),
                            ("editada", "Editada"),
                            ("finalizada", "Finalizada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="rooms.reserva",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Históricos de Reserva",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="CancelamentoReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField()),
                ("data_cancelamento", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelamentos_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancelamento",
                        to="rooms.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cancelamentos de Reservas",
            },
        ),
        migrations.AddIndex(
            model_name="sala",
            index=models.Index(
                fields=["ativa", "predio"], name="rooms_sala_ativa_ebee42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sala",
            index=models.Index(
                fields=["capacidade"], name="rooms_sala_capacid_187861_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sala",
            unique_together={("predio", "andar", "nome")},
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["sala", "data", "hora_inicio"],
                name="rooms_reser_sala_id_905c81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["professor", "data"], name="rooms_reser_profess_5792de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["data", "status"], name="rooms_reser_data_7055eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historicoreserva",
            index=models.Index(
                fields=["reserva", "data_hora"], name="rooms_histo_reserva_aba6bb_idx"
            ),
        ),
    ]
