# Generated by Django 4.2.13 on 2026-06-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationdismissal",
            new_name="core_notifi_user_id_cfe76a_idx",
            old_name="core_notifi_user_id_76d973_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationdismissal",
            new_name="core_notifi_reserva_c9730e_idx",
            old_name="core_notifi_reserva_3481b2_idx",
        ),
    ]
