# Generated by Django 4.2.13 on 2026-05-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Recursos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("predio", models.CharField(max_length=100)),
                ("andar", models.IntegerField()),
                ("capacidade", models.PositiveIntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("ativa", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "recursos",
                    models.ManyToManyField(
                        blank=True, related_name="salas", to="rooms.recurso"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Salas",
                "ordering": ["predio", "andar", "nome"],
                "indexes": [
                    models.Index(
                        fields=["ativa", "predio"], name="rooms_sala_ativa_ebee42_idx"
                    ),
                    models.Index(
                        fields=["capacidade"], name="rooms_sala_capacid_187861_idx"
                    ),
                ],
                "unique_together": {("predio", "andar", "nome")},
            },
        ),
    ]
