# Generated by Django on 2026-05-31
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="quantidade",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recurso",
            name="icone",
            field=models.CharField(default='videocam', help_text='Material Symbols icon name', max_length=50),
            preserve_default=False,
        ),
    ]
