# Generated by Django 4.2.13 on 2026-05-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_add_quantidade_recurso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurso",
            name="quantidade",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
