# Generated by Django 4.2.13 on 2026-05-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_recurso_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(default='videocam', help_text='Material Symbols icon name', max_length=50),
        ),
    ]
