# Generated by Django 4.2.13 on 2026-05-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_recurso_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='ativo',
        ),
    ]
